sudo: required
language: php
dist: trusty

services:
  - docker

php:
  - 7.1
  - 7.2
  - 7.3

# cache vendor dirs
cache:
  directories:
  - $HOME/.composer/cache

before_install:
  - wget http://packages.couchbase.com/releases/couchbase-release/couchbase-release-1.0-6-amd64.deb
  - sudo dpkg -i couchbase-release-1.0-6-amd64.deb
  - sudo apt-get -qq update
  - sudo apt-get install -y -y --no-install-recommends libssl1.0.0 libcouchbase-dev
  - pecl install couchbase
  - sudo wget https://packages.couchbase.com/releases/6.0.0/couchbase-server-community_6.0.0-ubuntu16.04_amd64.deb
  - sudo dpkg -i couchbase-server-community_6.0.0-ubuntu16.04_amd64.deb
  - sleep 10
  - sudo /opt/couchbase/bin/couchbase-cli cluster-init -c localhost:8091 -u Administrator -p password --cluster-ramsize=256 --service=data,index,query
  - sudo /opt/couchbase/bin/couchbase-cli bucket-create -c localhost:8091 -u Administrator -p password --bucket=default --bucket-ramsize=256 --bucket-replica=1

install:
- composer self-update && composer --version
- export PATH="$HOME/.composer/vendor/bin:$PATH"
- composer install --prefer-dist --no-interaction

script:
- sh ./phpcs.sh
- php ./vendor/bin/codecept run unit -d --coverage --coverage-xml

after_success:
- php ./vendor/bin/php-coveralls -v --exclude-no-stmt -c .coveralls.yml
